apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-notas-deployment
  labels:
    app: backend-notas-deployment
spec:
  selector:
    matchLabels:
      app: backend-notas-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: backend-notas-deployment
    spec:
      containers:
        - name: topeducation-notas
          image: jeremylm10748/topeducation-notas:latest
          ports:
            - containerPort: 8081
          env:
            - name: SPRING_CLOUD_CONFIG_URI
              value: http://backend-config-service:8081
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: http://backend-eureka-service:8761
            - name: eureka.instance.preferIpAddress
              value: "true"
            - name: POSTGRES_DS_HOST
              valueFrom:
                configMapKeyRef:
                  name: postgres-configmap
                  key: POSTGRES_DS_HOST
            - name: POSTGRES_DB_NOTAS
              valueFrom:
                configMapKeyRef:
                  name: postgres-configmap
                  key: POSTGRES_DB_NOTAS
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: postgres-configmap
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: POSTGRES_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: backend-notas-service
  labels:
    app: backend-notas-service
spec:
  selector:
    app: backend-notas-deployment
  ports:
    - protocol: TCP
      port: 8084
      targetPort: 8084
  type: LoadBalancer