apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-configmap
  labels:
    app: postgres-configmap
data:
  POSTGRES_DS_HOST: postgres
  POSTGRES_DB_HOST: postgres
  POSTGRES_DB_ESTUDIANTES: topeducationestudiantes
  POSTGRES_DB_CUOTAS: topeducationcuotas
  POSTGRES_DB_NOTAS: topeducationnotas
  POSTGRES_USER: postgres